apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-signing-helper
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-signing-helper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-signing-helper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-signing-helper
subjects:
- kind: ServiceAccount
  name: aws-signing-helper