apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-signing-helper-env
data:
  TRUST_ANCHOR_ARN: "arn:aws:rolesanywhere:....6:trust-anchor/...."
  PROFILE_ARN: "arn:aws:rolesanywhere:....:profile/...."
  ROLE_ARN: "arn:aws:iam::....:role/...."